name: Javadoc Builder
permissions:
  contents: read
on:
  release:
    types: [published]
jobs:
  build:
    name: Javadoc Builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up JDK 21
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version: 21
          distribution: 'corretto'
          cache: 'gradle'
      - name: Print JDK Version
        run: java -version
      - name: Make gradlew Executable
        run: chmod +x gradlew
      - name: Build javadocs
        run: ./gradlew --no-daemon --parallel javadoc
      - name: Upload javadocs
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: build/docs/javadoc
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy Javadoc
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
